import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import HeadView from "../home/header"
import FooterView from "../home/footer"



const index = () => {
    const validateFormWithJS = (e) => {
        e.preventDefault()
        var a =  document.querySelector('#first').value
        alert(a)
    }
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

       <HeadView /> 

        <div >
  <label for="first">First name:</label>
  <input type="text" id="first" name="first" />

  <label for="last">Last name:</label>
  <input type="text" id="last" name="last" />

  <button type="button" onClick={validateFormWithJS}>Submit</button>

        </div>

        <FooterView/>
      </main>
    
    </>
  )
}



export default index