import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HeadView from "../home/header"
import FooterView from "../home/footer"

const inter = Inter({ subsets: ['latin'] })



const index = () => {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

       <HeadView /> 

        <div className={styles.center}>
          Profile Page
        </div>

        <FooterView/>
      </main>
    
    </>
  )
}

export default index